services:
  - type: web
    name: vt-domain-checker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn vtchecker.wsgi --log-file -"
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "django-insecure-c689w0rhc%kbwnb6=-!o7c8bf@fp$lcki%@(k$zc$6os0w6neg"
    postDeploy:
      - python manage.py migrate
